-- AlterTable
ALTER TABLE "AbConfig" ADD COLUMN     "priceStars" INTEGER NOT NULL DEFAULT 350,
ADD COLUMN     "price3Stars" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN     "price6Stars" INTEGER NOT NULL DEFAULT 1500;
