-- AlterTable
ALTER TABLE "AbConfig" ADD COLUMN     "oldPrice" INTEGER NOT NULL DEFAULT 899,
ADD COLUMN     "oldPrice3" INTEGER NOT NULL DEFAULT 2697,
ADD COLUMN     "oldPrice6" INTEGER NOT NULL DEFAULT 5394,
ADD COLUMN     "price3" INTEGER NOT NULL DEFAULT 1799,
ADD COLUMN     "price6" INTEGER NOT NULL DEFAULT 2999,
ALTER COLUMN "price" SET DEFAULT 699;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "currentHeight" DOUBLE PRECISION,
ADD COLUMN     "initialBmi" DOUBLE PRECISION,
ADD COLUMN     "sleepLogs" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "subscriptionExpiry" TIMESTAMP(3),
ADD COLUMN     "waterLogs" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN     "weightLogs" JSONB NOT NULL DEFAULT '{}';
